apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  labels:
    name: kafka-pvc

spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: kafka-pv