apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafkalogs-pvc
  labels:
    name: kafkalogs-pvc

spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: kafkalogs-pv