apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: poc
  name: mysql-pvc
  labels:
    name: mysql-pvc

spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-pv
