apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  labels:
    name: zookeeper-pvc

spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: zookeeper-pv