apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: poc
  name: mysql
  labels:
    name: mysql

spec:
  selector: 
    matchLabels:
      name: mysql
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        name: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: mysql-config
        resources: {}
        livenessProbe: 
          exec:
            command:
              - "bash"
              - "-c"
              - "mysqladmin --user=root --password=${MYSQL_ROOT_PASSWORD} ping"
          initialDelaySeconds: 10
          timeoutSeconds: 20
          failureThreshold: 3
        readinessProbe: 
          exec:
            command: 
            - bash
            - -c
            - mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute="SHOW DATABASES;"
          initialDelaySeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-datadir
          persistentVolumeClaim:
            claimName: mysql-pvc
      restartPolicy: Always
      
