apiVersion: v1
kind: Service
metadata:
  namespace: poc
  name: mysql-service
  labels:
    name: mysql-service
spec:
  type: NodePort
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31000
    protocol: TCP
