apiVersion: v1
kind: Service
metadata:
  namespace: poc
  name: crud-service
  labels:
    name:  crud-service
spec:
  type: ClusterIP
  selector:
    name: crud-deploy
  ports:
  - port: 8088
    targetPort: 8088
