apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: poc
  name: mysql-pv
  labels:
    name:  mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /SharedFolder/mysql/data