apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  labels:
    name: zookeeper-pv
  
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /SharedFolder/zookeeper/data